// import { PrismaClient } from '@prisma/client';
// import jwt from 'jsonwebtoken';
// import archiver from 'archiver';
// import { PassThrough } from 'stream';

// const prisma = new PrismaClient();

// function verifyToken(req) {
//   const token = req.headers.get('authorization')?.split(' ')[1];
//   if (!token) return null;
//   try {
//     return jwt.verify(token, process.env.JWT_SECRET);
//   } catch {
//     return null;
//   }
// }

// function createPackageJson(projectName, frontend) {
//   const deps = frontend === 'next' ? {
//     next: '^14.0.0',
//     react: '^18.2.0',
//     'react-dom': '^18.2.0'
//   } : {
//     react: '^18.2.0'
//   };

//   return JSON.stringify({
//     name: projectName,
//     version: '0.1.0',
//     private: true,
//     scripts: frontend === 'next' ? {
//       dev: 'next dev',
//       build: 'next build',
//       start: 'next start'
//     } : {
//       start: 'react-scripts start',
//       build: 'react-scripts build'
//     },
//     dependencies: deps
//   }, null, 2);
// }

// function createReadme(projectName, config) {
//   return `# ${projectName}

// This project was generated by StackForge.

// Technology choices:
// - Frontend: ${config.frontend}
// - Backend: ${config.backend}
// - Database: ${config.database}
// - Auth: ${config.auth}

// Quick start:

// 1. Install dependencies

// ```bash
// npm install
// ```

// 2. Create a `.env` file and provide your backend connection string (if applicable):

// ```
// # Example .env
// BACKEND_URL=${config.backend === 'none' ? '"<no-backend>"' : 'http://localhost:3000'}
// ```

// 3. Run the dev server

// ```bash
// npm run dev
// ```

// Adjust backend configuration as needed.
// `;
// }

// export async function POST(req) {
//   try {
//     const decoded = verifyToken(req);
//     if (!decoded) {
//       return Response.json({ error: 'Unauthorized' }, { status: 401 });
//     }

//     const { projectName, config = {}, fields = [] } = await req.json();

//     if (!projectName || !config.frontend) {
//       return Response.json({ error: 'projectName and config.frontend are required' }, { status: 400 });
//     }

//     // Create an in-memory zip using archiver and stream it back
//     const stream = new PassThroughStream();
//     const archive = archiver('zip', { zlib: { level: 9 } });

//     archive.on('error', (err) => {
//       console.error('Archive error:', err);
//     });

//     archive.pipe(stream);

//     // Basic files
//     archive.append(createPackageJson(projectName, config.frontend), { name: 'package.json' });
//     archive.append(createReadme(projectName, config), { name: 'README.md' });
//     archive.append('.env.example\nBACKEND_URL=' + (config.backend === 'none' ? '' : 'http://localhost:3000') + '\n', { name: '.env.example' });

//     // Add minimal src depending on frontend
//     if (config.frontend === 'next') {
//       archive.append(`import './globals.css'

// export default function Home() {
//   return (<main><h1>Welcome to ${projectName}</h1></main>)
// }
// `, { name: 'app/page.jsx' });
//       archive.append('body { font-family: system-ui, sans-serif; }\n', { name: 'app/globals.css' });
//       archive.append("export default function RootLayout({ children }) { return (<html><body>{children}</body></html>) }\n", { name: 'app/layout.jsx' });
//     } else {
//       archive.append('<!doctype html>\n<html>\n  <head><meta charset="utf-8"><title>' + projectName + '</title></head>\n  <body><div id="root"></div><script src="src/index.js"></script></body>\n</html>\n', { name: 'public/index.html' });
//       archive.append("import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App';\nconst root = createRoot(document.getElementById('root'));\nroot.render(<App />);\n", { name: 'src/index.js' });
//       archive.append(`import React from 'react';
//     export default function App() { return (<div><h1>Welcome to ${projectName}</h1></div>);}
//     `, { name: 'src/App.jsx' });
//     }

//     // Add user-specified fields as a JSON file for reference
//     archive.append(JSON.stringify({ fields }, null, 2), { name: 'stackforge.config.json' });

//     await archive.finalize();

//     // Convert the PassThrough to a Response
//     const headers = new Headers();
//     headers.set('Content-Type', 'application/zip');
//     headers.set('Content-Disposition', `attachment; filename="${projectName}.zip"`);

//     return new Response(stream, { status: 200, headers });
//   } catch (error) {
//     console.error('Generate error:', error);
//     return Response.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
//   }
// }

// // Lightweight PassThrough stream implementation for Web/Node interop in Next app routes
// function PassThroughStream() {
//   return new PassThrough();
// }
export const runtime = 'nodejs';

import { PrismaClient } from '@prisma/client';
import jwt from 'jsonwebtoken';
import archiver from 'archiver';
import { PassThrough } from 'stream';

const prisma = new PrismaClient();

/* =========================
   AUTH VERIFICATION
========================= */
function verifyToken(req) {
  const authHeader = req.headers.get('authorization');
  if (!authHeader) return null;

  const token = authHeader.split(' ')[1];
  if (!token) return null;

  try {
    return jwt.verify(token, process.env.JWT_SECRET);
  } catch (err) {
    return null;
  }
}

/* =========================
   PACKAGE.JSON GENERATOR
========================= */
function createPackageJson(projectName, frontend) {
  const deps =
    frontend === 'next'
      ? {
          next: '^14.0.0',
          react: '^18.2.0',
          'react-dom': '^18.2.0'
        }
      : {
          react: '^18.2.0',
          'react-dom': '^18.2.0'
        };

  const scripts =
    frontend === 'next'
      ? {
          dev: 'next dev',
          build: 'next build',
          start: 'next start'
        }
      : {
          start: 'react-scripts start',
          build: 'react-scripts build'
        };

  return JSON.stringify(
    {
      name: projectName,
      version: '0.1.0',
      private: true,
      scripts,
      dependencies: deps
    },
    null,
    2
  );
}

/* =========================
   README GENERATOR
========================= */
function createReadme(projectName, config) {
  return `# ${projectName}

This project was generated by StackForge.

## 🚀 Tech Stack

- Frontend: ${config.frontend}
- Backend: ${config.backend || 'none'}
- Database: ${config.database || 'none'}
- Auth: ${config.auth || 'none'}

---

## 📦 Installation

\`\`\`bash
npm install
\`\`\`

---

## ⚙️ Environment Setup

Create a \`.env\` file:

\`\`\`
BACKEND_URL=${config.backend === 'none' ? '' : 'http://localhost:3000'}
\`\`\`

---

## ▶️ Run Project

\`\`\`bash
npm run dev
\`\`\`

---

Generated with ❤️ by StackForge.
`;
}

/* =========================
   MAIN API ROUTE
========================= */
export async function POST(req) {
  try {
    const decoded = verifyToken(req);
    if (!decoded) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { projectName, config = {}, fields = [] } = await req.json();

    if (!projectName || !config.frontend) {
      return Response.json(
        { error: 'projectName and config.frontend are required' },
        { status: 400 }
      );
    }

    /* =========================
       CREATE ZIP STREAM
    ========================= */
    const stream = new PassThrough();
    const archive = archiver('zip', { zlib: { level: 9 } });

    archive.on('error', (err) => {
      console.error('Archive error:', err);
      stream.destroy(err);
    });

    archive.pipe(stream);

    /* =========================
       BASIC FILES
    ========================= */
    archive.append(createPackageJson(projectName, config.frontend), {
      name: 'package.json'
    });

    archive.append(createReadme(projectName, config), {
      name: 'README.md'
    });

    archive.append(
      `BACKEND_URL=${
        config.backend === 'none' ? '' : 'http://localhost:3000'
      }\n`,
      { name: '.env.example' }
    );

    // Create a two-folder scaffold: frontend (Next.js) and backend (Express + Mongoose)
    // FRONTEND
    const frontendPath = 'frontend/';

    // frontend package.json
    archive.append(
      JSON.stringify(
        {
          name: `${projectName}-frontend`,
          version: '0.1.0',
          private: true,
          scripts: { dev: 'next dev', build: 'next build', start: 'next start' },
          dependencies: { next: '^14.0.0', react: '^18.2.0', 'react-dom': '^18.2.0', axios: '^1.4.0' }
        },
        null,
        2
      ),
      { name: frontendPath + 'package.json' }
    );

    // frontend next config and env
    archive.append("module.exports = { reactStrictMode: true }\n", { name: frontendPath + 'next.config.js' });
    archive.append('NEXT_PUBLIC_BACKEND_URL=http://localhost:3000\n', { name: frontendPath + '.env.local' });

    // frontend public folder (placeholder)
    archive.append('', { name: frontendPath + 'public/.gitkeep' });

    // frontend styles/globals.css
    archive.append(`* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  background-color: #f9fafb;
  color: #1f2937;
}

main, .container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 16px;
}

button {
  padding: 10px 20px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  background-color: #ffffff;
  cursor: pointer;
  font-size: 16px;
  transition: all 0.3s;
}

button:hover {
  background-color: #f3f4f6;
}

button.primary {
  background-color: #2563eb;
  color: white;
  border-color: #2563eb;
}

button.primary:hover {
  background-color: #1d4ed8;
}

input, textarea, select {
  padding: 8px 12px;
  border: 1px solid #d1d5db;
  border-radius: 6px;
  font-size: 16px;
  width: 100%;
}

input:focus {
  outline: none;
  border-color: #2563eb;
  box-shadow: 0 0 0 3px rgba(37, 99, 235, 0.1);
}
`, { name: frontendPath + 'styles/globals.css' });

    // frontend services/api.js
    archive.append(`import axios from 'axios';

const API_BASE_URL = process.env.NEXT_PUBLIC_BACKEND_URL || 'http://localhost:3000';

const api = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json'
  }
});

// Interceptor to add auth token
api.interceptors.request.use((config) => {
  const token = typeof window !== 'undefined' ? localStorage.getItem('auth_token') : null;
  if (token) {
    config.headers.Authorization = \`Bearer \${token}\`;
  }
  return config;
});

// Auth endpoints
export const authAPI = {
  signup: (data) => api.post('/auth/signup', data),
  login: (data) => api.post('/auth/login', data)
};

export default api;
`, { name: frontendPath + 'services/api.js' });

    // frontend context/AuthContext.js
    archive.append(`'use client';
import { createContext, useState, useContext, useEffect } from 'react';

const AuthContext = createContext();

export function AuthProvider({ children }) {
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const token = localStorage.getItem('auth_token');
    if (token) {
      setUser({ authenticated: true });
    }
    setLoading(false);
  }, []);

  const logout = () => {
    localStorage.removeItem('auth_token');
    setUser(null);
  };

  return (
    <AuthContext.Provider value={{ user, loading, logout }}>
      {children}
    </AuthContext.Provider>
  );
}

export const useAuth = () => {
  const context = useContext(AuthContext);
  if (!context) {
    throw new Error('useAuth must be used inside AuthProvider');
  }
  return context;
};
`, { name: frontendPath + 'context/AuthContext.js' });

    // frontend components/Navbar.jsx
    archive.append(`'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useAuth } from '@/context/AuthContext';

export default function Navbar() {
  const { user, logout } = useAuth();
  const router = useRouter();

  const handleLogout = () => {
    logout();
    router.push('/');
  };

  return (
    <nav style={{
      padding: '16px 0',
      borderBottom: '1px solid #e5e7eb',
      marginBottom: '32px'
    }}>
      <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '0 16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Link href="/" style={{ fontSize: '24px', fontWeight: 'bold', textDecoration: 'none', color: '#1f2937' }}>
          ${projectName}
        </Link>
        <div style={{ display: 'flex', gap: '16px', alignItems: 'center' }}>
          {user ? (
            <>
              <Link href="/dashboard" style={{ textDecoration: 'none', color: '#2563eb' }}>
                Dashboard
              </Link>
              <button onClick={handleLogout} style={{ background: '#ef4444', color: 'white', borderColor: '#ef4444' }}>
                Logout
              </button>
            </>
          ) : (
            <>
              <Link href="/login" style={{ textDecoration: 'none', color: '#2563eb' }}>
                Login
              </Link>
              <Link href="/signup" style={{ textDecoration: 'none', color: '#fff', background: '#2563eb', padding: '10px 20px', borderRadius: '6px' }}>
                Sign Up
              </Link>
            </>
          )}
        </div>
      </div>
    </nav>
  );
}
`, { name: frontendPath + 'components/Navbar.jsx' });

    // frontend components/AuthForm.jsx
    archive.append(`'use client';
import { useState } from 'react';
import { authAPI } from '@/services/api';

export default function AuthForm({ type = 'login', onSuccess }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({});

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');

    try {
      const endpoint = type === 'login' ? authAPI.login : authAPI.signup;
      const response = await endpoint(formData);
      localStorage.setItem('auth_token', response.data.token);
      onSuccess?.();
    } catch (err) {
      setError(err.response?.data?.error || 'An error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <form onSubmit={handleSubmit} style={{ maxWidth: '400px', margin: '0 auto' }}>
      {error && <div style={{ color: '#dc2626', marginBottom: '16px', padding: '12px', backgroundColor: '#fee2e2', borderRadius: '6px' }}>{error}</div>}
      {formData && Object.keys(formData).map(key => key)}
      <button type="submit" disabled={loading} className="primary" style={{ width: '100%', marginTop: '20px' }}>
        {loading ? 'Processing...' : (type === 'login' ? 'Login' : 'Sign Up')}
      </button>
    </form>
  );
}
`, { name: frontendPath + 'components/AuthForm.jsx' });

    // frontend app layout (updated)
    archive.append(
      `'use client';
import { AuthProvider } from '@/context/AuthContext';
import Navbar from '@/components/Navbar';
import '@/styles/globals.css';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Navbar />
          <main style={{ minHeight: 'calc(100vh - 80px)' }}>
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
`,
      { name: frontendPath + 'app/layout.jsx' }
    );

    // build form inputs function for AuthForm (fields shown dynamically)
    const buildFormFields = (fieldsArray) => {
      return fieldsArray
        .filter(f => f.name !== 'password')
        .map(f => `<div style={{marginBottom: '16px'}}>
        <label style={{display: 'block', marginBottom: '8px', fontWeight: '500'}}>${f.name.charAt(0).toUpperCase() + f.name.slice(1)}</label>
        <input type="text" name="${f.name}" onChange={handleChange} required style={{width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '6px'}} />
      </div>`)
        .join('\n');
    };

    const frontendLogin = `'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { authAPI } from '@/services/api';

export default function Login() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({});

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const response = await authAPI.login(formData);
      localStorage.setItem('auth_token', response.data.token);
      router.push('/dashboard');
    } catch (err) {
      setError(err.response?.data?.error || 'Login failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '500px', margin: '0 auto', padding: '40px 20px' }}>
      <h1 style={{ marginBottom: '32px', textAlign: 'center' }}>Login</h1>
      {error && <div style={{ color: '#dc2626', marginBottom: '16px', padding: '12px', backgroundColor: '#fee2e2', borderRadius: '6px' }}>{error}</div>}
      <form onSubmit={handleSubmit}>
        ${buildFormFields(fields)}
        <div style={{marginBottom: '16px'}}>
          <label style={{display: 'block', marginBottom: '8px', fontWeight: '500'}}>Password</label>
          <input type="password" name="password" required onChange={handleChange} style={{width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '6px'}} />
        </div>
        <button type="submit" disabled={loading} style={{width: '100%', padding: '12px', backgroundColor: '#2563eb', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: '500'}}>
          {loading ? 'Processing...' : 'Login'}
        </button>
      </form>
      <p style={{ textAlign: 'center', marginTop: '16px' }}>
        Don't have an account? <a href="/signup" style={{ color: '#2563eb', textDecoration: 'none' }}>Sign up</a>
      </p>
    </div>
  );
}
`;

    const frontendSignup = `'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { authAPI } from '@/services/api';

export default function Signup() {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [formData, setFormData] = useState({});

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({ ...prev, [name]: value }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    try {
      const response = await authAPI.signup(formData);
      localStorage.setItem('auth_token', response.data.token);
      router.push('/dashboard');
    } catch (err) {
      setError(err.response?.data?.error || 'Signup failed');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ maxWidth: '500px', margin: '0 auto', padding: '40px 20px' }}>
      <h1 style={{ marginBottom: '32px', textAlign: 'center' }}>Create Account</h1>
      {error && <div style={{ color: '#dc2626', marginBottom: '16px', padding: '12px', backgroundColor: '#fee2e2', borderRadius: '6px' }}>{error}</div>}
      <form onSubmit={handleSubmit}>
        ${buildFormFields(fields)}
        <div style={{marginBottom: '16px'}}>
          <label style={{display: 'block', marginBottom: '8px', fontWeight: '500'}}>Password</label>
          <input type="password" name="password" required onChange={handleChange} style={{width: '100%', padding: '8px 12px', border: '1px solid #d1d5db', borderRadius: '6px'}} />
        </div>
        <button type="submit" disabled={loading} style={{width: '100%', padding: '12px', backgroundColor: '#2563eb', color: 'white', border: 'none', borderRadius: '6px', cursor: 'pointer', fontWeight: '500'}}>
          {loading ? 'Processing...' : 'Sign Up'}
        </button>
      </form>
      <p style={{ textAlign: 'center', marginTop: '16px' }}>
        Already have an account? <a href="/login" style={{ color: '#2563eb', textDecoration: 'none' }}>Login</a>
      </p>
    </div>
  );
}
`;

    archive.append(frontendLogin, { name: frontendPath + 'app/login/page.jsx' });
    archive.append(frontendSignup, { name: frontendPath + 'app/signup/page.jsx' });
    archive.append(`'use client';
export default function Home() {
  return (
    <div style={{ textAlign: 'center', padding: '60px 20px' }}>
      <h1 style={{ fontSize: '48px', fontWeight: 'bold', marginBottom: '16px' }}>Welcome to ${projectName}</h1>
      <p style={{ fontSize: '18px', color: '#6b7280', marginBottom: '32px' }}>
        A full-stack application with modern authentication
      </p>
      <div style={{ display: 'flex', gap: '16px', justifyContent: 'center' }}>
        <a href="/login" style={{ padding: '12px 24px', backgroundColor: '#2563eb', color: 'white', textDecoration: 'none', borderRadius: '6px' }}>
          Login
        </a>
        <a href="/signup" style={{ padding: '12px 24px', backgroundColor: '#e5e7eb', color: '#1f2937', textDecoration: 'none', borderRadius: '6px' }}>
          Sign Up
        </a>
      </div>
    </div>
  );
}
`, { name: frontendPath + 'app/page.jsx' });

    // frontend dashboard (post-auth page)
    const frontendDashboard = `'use client';
import { useRouter } from 'next/navigation';
import { useState, useEffect } from 'react';
import PostsTable from '@/components/PostTable';
import { postsAPI } from '@/services/postsAPI';

export default function Dashboard() {
  const router = useRouter();
  const [user, setUser] = useState(null);
  const [loading, setLoading] = useState(true);
  const [posts, setPosts] = useState([]);

  useEffect(() => {
    const token = localStorage.getItem('auth_token');
    if (!token) {
      router.push('/login');
    } else {
      setUser({ authenticated: true });
      setLoading(false);
      fetchPosts();
    }
  }, [router]);

  const fetchPosts = async () => {
    try {
      const res = await postsAPI.getPosts();
      setPosts(res.data || res);
    } catch (err) {
      console.error(err);
    }
  };

  const handleLogout = () => {
    localStorage.removeItem('auth_token');
    router.push('/login');
  };

  if (loading) {
    return <div style={{ padding: '40px', textAlign: 'center' }}>Loading...</div>;
  }

  return user ? (
    <div style={{ maxWidth: '1200px', margin: '0 auto', padding: '40px 20px' }}>
      <h1 style={{ marginBottom: '24px' }}>Dashboard</h1>
      <div style={{ marginBottom: '16px' }}>
        <button onClick={handleLogout} style={{ padding: '10px 16px', backgroundColor: '#ef4444', color: 'white', border: 'none', borderRadius: '6px' }}>Logout</button>
      </div>
      <PostsTable posts={posts} refresh={fetchPosts} />
    </div>
  ) : (
    <div style={{ padding: '40px', textAlign: 'center' }}>Redirecting to login...</div>
  );
}
`;
    archive.append(frontendDashboard, { name: frontendPath + 'app/dashboard/page.jsx' });

    // include stackforge.config.json in frontend for reference
    archive.append(JSON.stringify({ fields }, null, 2), { name: frontendPath + 'stackforge.config.json' });

    // frontend posts API wrapper
    archive.append(
      "import api from './api';\n\nexport const postsAPI = {\n  getPosts: () => api.get('/api/posts'),\n  createPost: (data) => api.post('/api/posts', data),\n  updatePost: (id, data) => api.put('/api/posts/' + id, data),\n  deletePost: (id) => api.delete('/api/posts/' + id)\n};\n",
      { name: frontendPath + 'services/postsAPI.js' }
    );

    // frontend PostTable component
    archive.append(
      `'use client';\nimport React from 'react';\n\nexport default function PostTable({ posts = [], refresh }) {\n  return (\n    <div>\n      <h2 style={{ marginBottom: '12px' }}>Posts</h2>\n      {posts.length === 0 ? (\n        <div>No posts yet.</div>\n      ) : (\n        <table style={{ width: '100%', borderCollapse: 'collapse' }}>\n          <thead>\n            <tr>\n              <th style={{ textAlign: 'left', padding: '8px', borderBottom: '1px solid #e5e7eb' }}>Title</th>\n              <th style={{ textAlign: 'left', padding: '8px', borderBottom: '1px solid #e5e7eb' }}>Description</th>\n            </tr>\n          </thead>\n          <tbody>\n            {posts.map(p => (\n              <tr key={p._id}>\n                <td style={{ padding: '8px', borderBottom: '1px solid #f3f4f6' }}>{p.title}</td>\n                <td style={{ padding: '8px', borderBottom: '1px solid #f3f4f6' }}>{p.description}</td>\n              </tr>\n            ))}\n          </tbody>\n        </table>\n      )}\n    </div>\n  );\n}\n`,
      { name: frontendPath + 'components/PostTable.jsx' }
    );

    // BACKEND
    const backendPath = 'backend/';
    archive.append(
      JSON.stringify(
        {
          name: `${projectName}-backend`,
          version: '0.1.0',
          private: true,
          scripts: { dev: 'nodemon server.js', start: 'node server.js' },
          dependencies: { express: '^4.18.2', mongoose: '^7.0.0', bcrypt: '^5.1.0', jsonwebtoken: '^9.0.0', dotenv: '^16.0.0', cors: '^2.8.5' },
          devDependencies: { nodemon: '^2.0.22' }
        },
        null,
        2
      ),
      { name: backendPath + 'package.json' }
    );

    archive.append('PORT=3000\nDATABASE_URL=\nJWT_SECRET=your_jwt_secret\n', { name: backendPath + '.env.example' });

    // backend server.js
    archive.append(
      `const express = require('express');\nconst cors = require('cors');\nconst dotenv = require('dotenv');\nconst connectDB = require('./config/db');\nconst authRoutes = require('./routes/authRoutes');\nconst postRoutes = require('./routes/postRoutes');\n\ndotenv.config();\nconst app = express();\napp.use(cors());\napp.use(express.json());\nconnectDB();\napp.use('/auth', authRoutes);\n// mount generated API routes\napp.use('/api/posts', postRoutes);\nconst port = process.env.PORT || 3000;\napp.listen(port, () => console.log('Server running on', port));\n`,
      { name: backendPath + 'server.js' }
    );
    
    // register posts route in server.js as well (we'll create the file below)
    archive.append(
      `// Note: post routes are registered below when files are created\n// To use posts API mount like: app.use('/api/posts', require('./routes/postRoutes'));\n`,
      { name: backendPath + 'server-note.txt' }
    );

    // backend config/db.js
    archive.append(
      `const mongoose = require('mongoose');\nmodule.exports = function connectDB(){\n  const url = process.env.DATABASE_URL;\n  if(!url) { console.warn('No DATABASE_URL set'); return; }\n  mongoose.connect(url).then(()=>console.log('MongoDB connected')).catch(err=>console.error(err));\n};\n`,
      { name: backendPath + 'config/db.js' }
    );

    // backend models/User.js
    const userSchemaFields = fields
      .filter(f => f.name !== 'password' && f.name !== 'passwordHash')
      .map(f => `${f.name}: { type: String, required: true }`)
      .join(',\n  ');

    const userModel = `const mongoose = require('mongoose');\nconst Schema = mongoose.Schema;\nconst UserSchema = new Schema({\n  ${userSchemaFields},\n  passwordHash: { type: String, required: true },\n  createdAt: { type: Date, default: Date.now }\n});\nmodule.exports = mongoose.model('User', UserSchema);\n`;

    archive.append(userModel, { name: backendPath + 'models/User.js' });

    // utils/generateToken.js
    archive.append(
      `const jwt = require('jsonwebtoken');\nmodule.exports = function generateToken(user){\n  return jwt.sign({ id: user._id, email: user.email }, process.env.JWT_SECRET || 'secret', { expiresIn: '7d' });\n};\n`,
      { name: backendPath + 'utils/generateToken.js' }
    );

    // controllers/authController.js
    archive.append(
      `const bcrypt = require('bcrypt');\nconst User = require('../models/User');\nconst generateToken = require('../utils/generateToken');\n\nexports.signup = async (req, res) => {\n  try {\n    const data = req.body;\n    if(!data.password) return res.status(400).json({ error: 'Password required' });\n    const salt = await bcrypt.genSalt(10);\n    const hash = await bcrypt.hash(data.password, salt);\n    const userData = { ...data, passwordHash: hash };\n    delete userData.password;\n    const user = await User.create(userData);\n    const token = generateToken(user);\n    res.json({ token });\n  } catch (err) { console.error(err); res.status(500).json({ error: err.message }); }\n};\n\nexports.login = async (req, res) => {\n  try {\n    const { email, password } = req.body;\n    const user = await User.findOne({ email });\n    if(!user) return res.status(400).json({ error: 'Invalid credentials' });\n    const valid = await bcrypt.compare(password, user.passwordHash);\n    if(!valid) return res.status(400).json({ error: 'Invalid credentials' });\n    const token = generateToken(user);\n    res.json({ token });\n  } catch (err) { console.error(err); res.status(500).json({ error: err.message }); }\n};\n`,
      { name: backendPath + 'controllers/authController.js' }
    );

    // routes/authRoutes.js
    archive.append(
      `const express = require('express');\nconst router = express.Router();\nconst { signup, login } = require('../controllers/authController');\nrouter.post('/signup', signup);\nrouter.post('/login', login);\nmodule.exports = router;\n`,
      { name: backendPath + 'routes/authRoutes.js' }
    );

    // simple auth middleware
    archive.append(
      `const jwt = require('jsonwebtoken');\nmodule.exports = function (req,res,next){\n  const auth = req.headers.authorization;\n  if(!auth) return res.status(401).json({ error: 'Unauthorized' });\n  const token = auth.split(' ')[1];\n  try{ const dec = jwt.verify(token, process.env.JWT_SECRET); req.user = dec; next(); } catch(e){ res.status(401).json({ error: 'Unauthorized' }); }\n};\n`,
      { name: backendPath + 'middleware/authMiddleware.js' }
    );

    // ======= Generate Post model, controller, routes based on user fields =======
    const postSchemaFields = fields
      .map(f => `${f.name}: { type: String${f.required ? ', required: true' : ''} }`)
      .join(',\\n  ');

    const postModel = `const mongoose = require('mongoose');\\nconst Schema = mongoose.Schema;\\nconst PostSchema = new Schema({\\n  ${postSchemaFields || "title: { type: String, required: true }"}\\n});\\nmodule.exports = mongoose.model('Post', PostSchema);\\n`;

    archive.append(postModel, { name: backendPath + 'models/Post.js' });

    const postController = `const Post = require('../models/Post');\\n\\nexports.createPost = async (req, res) => {\\n  try {\\n    const post = await Post.create(req.body);\\n    res.status(201).json(post);\\n  } catch (err) { console.error(err); res.status(500).json({ error: err.message }); }\\n};\\n\\nexports.getPosts = async (req, res) => {\\n  try {\\n    const posts = await Post.find().sort({ createdAt: -1 });\\n    res.json(posts);\\n  } catch (err) { console.error(err); res.status(500).json({ error: err.message }); }\\n};\\n\\nexports.updatePost = async (req, res) => {\\n  try {\\n    const post = await Post.findByIdAndUpdate(req.params.id, req.body, { new: true });\\n    if(!post) return res.status(404).json({ error: 'Not found' });\\n    res.json(post);\\n  } catch (err) { console.error(err); res.status(500).json({ error: err.message }); }\\n};\\n\\nexports.deletePost = async (req, res) => {\\n  try {\\n    const post = await Post.findByIdAndDelete(req.params.id);\\n    if(!post) return res.status(404).json({ error: 'Not found' });\\n    res.json({ success: true });\\n  } catch (err) { console.error(err); res.status(500).json({ error: err.message }); }\\n};\\n`;

    archive.append(postController, { name: backendPath + 'controllers/postController.js' });

    const postRoutes = `const express = require('express');\\nconst router = express.Router();\\nconst { createPost, getPosts, updatePost, deletePost } = require('../controllers/postController');\\nconst auth = require('../middleware/authMiddleware');\\n\\nrouter.post('/', auth, createPost);\\nrouter.get('/', auth, getPosts);\\nrouter.put('/:id', auth, updatePost);\\nrouter.delete('/:id', auth, deletePost);\\n\\nmodule.exports = router;\\n`;

    archive.append(postRoutes, { name: backendPath + 'routes/postRoutes.js' });

    // Append a small server patch that instructs mounting posts router
    const serverPatch = `\n// Mount API routes\nconst postRoutes = require('./routes/postRoutes');\napp.use('/api/posts', postRoutes);\n`;
    archive.append(serverPatch, { name: backendPath + 'server-mount-posts.js' });

    /* =========================
       USER SCHEMA FILE
    ========================= */
    archive.append(JSON.stringify({ fields }, null, 2), {
      name: 'stackforge.config.json'
    });

    // Create root-level README
    const cliCommand = `npx stackforge create ${projectName.toLowerCase().replace(/\s+/g, '-')}`;

    // Create root-level README
    const rootReadme = `# ${projectName}

**Generated by StackForge**

This is a full-stack application with a Next.js frontend and an Express + Mongoose backend.

## 📁 Project Structure

\`\`\`
${projectName}/
├── frontend/          # Next.js application
│   ├── package.json
│   ├── .env.local     # Set NEXT_PUBLIC_BACKEND_URL here
│   ├── app/
│   │   ├── page.jsx                 # Home page
│   │   ├── login/page.jsx           # Login form
│   │   ├── signup/page.jsx          # Sign up form
│   │   ├── dashboard/page.jsx       # Protected dashboard
│   │   └── layout.jsx               # Root layout
│   └── stackforge.config.json       # Field configuration (reference)
│
└── backend/           # Express API server
    ├── package.json
    ├── .env.example   # Copy to .env and fill in values
    ├── server.js
    ├── config/
    │   └── db.js      # MongoDB connection
    ├── models/
    │   └── User.js    # User schema (auto-generated with your fields)
    ├── controllers/
    │   └── authController.js
    ├── routes/
    │   └── authRoutes.js
    ├── middleware/
    │   └── authMiddleware.js
    └── utils/
        └── generateToken.js
\`\`\`

## 🚀 Quick Start

### Prerequisites
- Node.js 18+
- MongoDB (local or cloud)

### 1. Backend Setup

\`\`\`bash
cd backend
cp .env.example .env
\`\`\`

Edit \`.env\` and fill in:
\`\`\`
PORT=3000
DATABASE_URL=mongodb+srv://<user>:<password>@<cluster>.mongodb.net/<dbname>
JWT_SECRET=your_secret_key_here
\`\`\`

Install and run:
\`\`\`bash
npm install
npm run dev
\`\`\`

Server runs on http://localhost:3000

### 2. Frontend Setup

In a new terminal:

\`\`\`bash
cd frontend
npm install
\`\`\`

Edit \`.env.local\`:
\`\`\`
NEXT_PUBLIC_BACKEND_URL=http://localhost:3000
\`\`\`

Run:
\`\`\`bash
npm run dev
\`\`\`

Frontend runs on http://localhost:3000 (or next available port)

## 🔐 Authentication Flow

1. **Signup**: POST \`/auth/signup\` with user data
   - Select fields: ${fields.map(f => f.name).join(', ')}
   - Password is hashed with bcrypt

2. **Login**: POST \`/auth/login\` with email + password
   - Returns JWT token

3. **Protected Routes**: Include \`Authorization: Bearer <token>\` header

## 📚 API Endpoints

### Auth
- \`POST /auth/signup\` - Create account
- \`POST /auth/login\` - Login

Request body:
\`\`\`json
{
  ${fields.filter(f => f.name !== 'password').map(f => '"' + f.name + '": "value"').join(',\n  ')},
  "password": "..."
}
\`\`\`

Response:
\`\`\`json
{
  "token": "eyJhbGciOiJIUzI1NiIs..."
}
\`\`\`

## 🛠 Tech Stack

- **Frontend**: Next.js 14, React 18, Axios
- **Backend**: Express.js, Mongoose, JWT, Bcrypt
- **Database**: MongoDB
- **Auth**: JWT + Bcrypt

## 📝 Environment Variables

### Backend (\`.env\`)
\`\`\`
PORT=3000
DATABASE_URL=<your-mongodb-connection-string>
JWT_SECRET=<your-secret-key>
\`\`\`

### Frontend (\`.env.local\`)
\`\`\`
NEXT_PUBLIC_BACKEND_URL=http://localhost:3000
\`\`\`

## 🧪 Testing Auth

**Signup:**
\`\`\`bash
curl -X POST http://localhost:3000/auth/signup \\
  -H "Content-Type: application/json" \\
  -d '{
    ${fields.filter(f => f.name !== 'password').map(f => '"' + f.name + '": "value"').join(',\n    ')},
    "password": "test123"
  }'
\`\`\`

**Login:**
\`\`\`bash
curl -X POST http://localhost:3000/auth/login \\
  -H "Content-Type: application/json" \\
  -d '{
    "email": "user@example.com",
    "password": "test123"
  }'
\`\`\`

## 📖 Learn More

- [Next.js Docs](https://nextjs.org/docs)
- [Express.js Guide](https://expressjs.com/)
- [Mongoose Documentation](https://mongoosejs.com/docs/guide.html)

---

Happy coding! 🎉
`;

    archive.append(rootReadme, { name: 'README.md' });
    archive.append('.gitignore\nnode_modules/\n.env\n.env.local\n.next/\ndist/\nbuild/\n', { name: '.gitignore' });

    // Finalize archive AFTER all files appended
    await archive.finalize();

    // Save project to database so it appears in history
    const project = await prisma.project.create({
      data: {
        userId: decoded.id,
        projectName: projectName,
        config: config,
        cliCommand: cliCommand,
        status: 'completed',
        fields: fields
      }
    });

    console.log('Project saved to DB:', project.id);

    /* =========================
       RETURN ZIP RESPONSE
    ========================= */
    return new Response(stream, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${projectName}.zip"`,
        'X-Project-Id': project.id
      }
    });
  } catch (error) {
    console.error('Generate error:', error);
    return Response.json(
      { error: error.message || 'Internal Server Error' },
      { status: 500 }
    );
  }
}