import { PrismaClient } from '@prisma/client';
import jwt from 'jsonwebtoken';
import archiver from 'archiver';
import { PassThrough } from 'stream';

const prisma = new PrismaClient();

// token helper shared across project routes
function verifyToken(req) {
  const token = req.headers.get('authorization')?.split(' ')[1];
  if (!token) return null;
  try {
    return jwt.verify(token, process.env.JWT_SECRET);
  } catch {
    return null;
  }
}

// create a zip stream given project details; duplicate of generate logic
// so that downloads can be regenerated on demand
function buildZipStream(projectName, config, fields = []) {
  const stream = new PassThrough();
  const archive = archiver('zip', { zlib: { level: 9 } });

  archive.on('error', (err) => {
    console.error('Archive error:', err);
    stream.destroy(err);
  });

  archive.pipe(stream);

  // base files
  archive.append(JSON.stringify({ name: projectName, version: '1.0.0' }, null, 2), {
    name: 'package.json'
  });
  archive.append(`# ${projectName}

Generated by StackForge
`, { name: 'README.md' });
  archive.append(
    `BACKEND_URL=${
      config.backend === 'none' ? '' : 'http://localhost:3000'
    }\n`,
    { name: '.env.example' }
  );

  // frontend scaffold
  if (config.frontend === 'next') {
    archive.append(
      `import './globals.css'

export default function Home() {
  return (
    <main style={{ padding: "40px", fontFamily: "system-ui" }}>
      <h1>Welcome to ${projectName}</h1>
    </main>
  );
}
`,
      { name: 'app/page.jsx' }
    );
    archive.append(
      `export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
      { name: 'app/layout.jsx' }
    );
    archive.append(`body {
  font-family: system-ui, sans-serif;
}
`, { name: 'app/globals.css' });
  } else {
    archive.append(
      `<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${projectName}</title>
  </head>
  <body>
    <div id="root"></div>
    <script src="src/index.js"></script>
  </body>
</html>
`,
      { name: 'public/index.html' }
    );
    archive.append(
      `import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';

const root = createRoot(document.getElementById('root'));
root.render(<App />);
`,
      { name: 'src/index.js' }
    );
    archive.append(
      `import React from 'react';

export default function App() {
  return (
    <div style={{ padding: "40px", fontFamily: "system-ui" }}>
      <h1>Welcome to ${projectName}</h1>
    </div>
  );
}
`,
      { name: 'src/App.jsx' }
    );
  }

  // store configuration
  archive.append(JSON.stringify({ fields }, null, 2), {
    name: 'stackforge.config.json'
  });

  archive.finalize();
  return stream;
}

export async function GET(req, { params }) {
  try {
    const decoded = verifyToken(req);
    if (!decoded) {
      return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 });
    }

    // params may be a Promise in App Router; unwrap to access id
    const { id } = await params;

    const project = await prisma.project.findFirst({
      where: {
        id: id,
        userId: decoded.id
      }
    });

    if (!project) {
      return new Response(JSON.stringify({ error: 'Project not found' }), { status: 404 });
    }

    const stream = buildZipStream(project.projectName, project.config, project.fields || []);

    return new Response(stream, {
      status: 200,
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${project.projectName}.zip"`
      }
    });
  } catch (err) {
    console.error('Zip download error:', err);
    return new Response(JSON.stringify({ error: err.message || 'Internal' }), { status: 500 });
  }
}
